- name: Instalando Pacote DEB
  command: 'dpkg -i /puppet6-release-bionic.deb'          
  when: ansible_os_family == 'Debian'

- name: Instalando Puppet Agent - Ubuntu
  apt:
    name: puppet-agent
    update_cache: yes
    state: present
